from rest_framework import serializers
from .models import User

class UserSerializer(serializers.ModelSerializer):
    class Meta:
        model = User
        # id field is autogenerated by django. naes must match models in models.py
        fields = ["id", "userName", "email", "picture"]